# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform_fmt:
    name: 'Terraform Format'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform -chdir="tf-gcp-infra" fmt -check -diff

  terraform_plan_dev:
    name: 'Terraform Dev Plan'
    runs-on: ubuntu-latest
    needs: 'terraform_fmt'
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Setup the GCP Storage Account credentials
    - name: Storage Account Credentials
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.tf_nonprod_state_sa_creds }}'

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir="tf-gcp-infra" init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform -chdir="tf-gcp-infra" plan -input=false -var-file="nonprod.tfvars"

  terraform_apply_dev:
    name: 'Terraform Apply'
    needs: 'terraform_plan_dev'
    runs-on: ubuntu-latest
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Setup the GCP Storage Account credentials
      - name: Storage Account Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.tf_nonprod_state_sa_creds }}'

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform -chdir="tf-gcp-infra" init
                   
      - name: Terraform Plan
        # if: github.ref == 'refs/heads/"main"' # && github.event_name == 'push'
        run: terraform -chdir="tf-gcp-infra" plan -input=false -var-file="nonprod.tfvars"

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/"main"' # && github.event_name == 'push'
        run: terraform -chdir="tf-gcp-infra" apply -auto-approve -input=false -var-file="nonprod.tfvars"

